### ISSUE TITLE
Documentation missing for schemaName knex configuration option

### ISSUE THREAD

**Issue by elhigu** [knex/documentation#101]
Pull request that added feature is here: https://github.com/tgriesser/knex/pull/2559

**Comment by kibertoad** [comment]
@elhigu PR is up! Btw, any chance I could get write permissions for the knex-documentation repo? Syncing personal fork each time to make a change is not very convenient, branching out from main repo is so much more convenient :).

**Comment by elhigu** [comment]
Thanks and great! 

I have never encountered problems of having to sync my own fork (I don't keep it in sync at all). 

I just work with multiple remotes in a way that I pull code from upstream repo, modify it and push it to my own fork just for creating pull requests. Something like this:

```
git remote add origin https://elhigu@github.com/knex/documentation.git
git remote add elhigu https://elhigu@github.com/elhigu/documentation.git

git remote update
# get clean copy from upstream to work with
git checkout origin/gh-pages -b gh-pages 

# do my changes

git push elhigu gh-pages:my-new-feature-branch-containing-changes-for-creating-pull-request
```

I've always felt that keeping forks in sync is a bit painful / useless since I always like to write my work on top of upstream. So I always work against upstream and just use forks for publishing stuff for PRs.

Also I don't like using the upstream repo for feature branches of every PR, because it litters upstrean repo unnecessarily. When feature branch is once pushed to upstream repo it will stay there forever and cannot be deleted completely after PR is merged (maybe there is some way that I don't know which allows to completely erase branch from existense?).

**Comment by elhigu** [comment]
Anyways I'll add you write rights, you might need them for something else 👍

**Comment by igor-savin-ht** [comment]
Thanks, I'll try doing it your way!

**Comment by elhigu** [comment]
All PRs for 0.14.5 are now merged and docs rebuilt.
