### ISSUE TITLE
Migrations Cause MySQL Dialect Warning

### ISSUE THREAD

**Issue by travistrue2008** [knex/documentation#121]
Whenever I run MySQL migrations, I get the following warning: ```To get rid of this warning you should specify the mysql dialect version in your knex configuration. Currently this defaults to 5.5, but in a future release it will default to 5.6 which supports high precision timestamps. See http://knexjs.org/#Schema-timestamps for more information.```

I'd set the dialect version, but I don't know where to do that. I did some searching online, but came up with nothing. That link in the warning description just explains MySQL version requirements for low vs high-precision timestamps. I am running MySQL 5.7.21, so I'm all set there. I just need to figure out how to inform Knex of which dialect version to use in my _knexfile_.

Here is my _knexfile_:
```
// provide ES6 support
require('babel-register')
require('babel-polyfill')

// load the config file
const configPath = (process.env.NODE_ENV === 'production') ? './config' : './config'
const config = require(configPath)

// export the config
module.exports = {
  client: 'mysql',
  connection: config.MYSQL,
  pool: {
    min: 1,
    max: 10,
  },
  migrations: {
    directory: './migrations',
    stub: './migration.tpl.js',
  },
}
```

**Comment by elhigu** [comment]
Its in knex documentation page. 0.15.0 docs has the info. Try refreshing the page... version attribute goes to same level with client attribute

**Comment by travistrue2008** [comment]
@elhigu Woah, I can't believe I missed that. I remember specifically looking for `version`, and only getting like 2 results, when I checked this time, it came right now. Furthermore, I remember reading that documentation in the past, so I can't believe that went right over my head.

Thanks for the help!

**Comment by travistrue2008** [comment]
I'd hate to re-open this, but I noticed that the warning still appears after setting the appropriate version. Here's my _knexfile.js_:
```
module.exports = {
  client: 'mysql',
  version: '5.7',
  connection: config.MYSQL,
}
```

**Comment by elhigu** [comment]
@travistrue2008 Thanks for the report, I'll try adding version specifier to knex's test configuration and now that we have a way to override log handlers I can also check that warnings are not shown anymore when version attribute is passed to the config 👍

**Comment by elhigu** [comment]
@travistrue2008 I just tried adding version: '5.7' parameter to test configuration and error message vanished, so I would claim that the error is in your code or there is some special case where it triggers anyways. 

However I'll add the testcase for it anyways.
