### ISSUE TITLE
0.16.2 is out on npm but new docs aren't published

### ISSUE THREAD

**Issue by fl0w** [knex/documentation#157]
Not sure if intentional but figured I'd drop a reminder.

**Comment by elhigu** [comment]
I haven't got time... its my next task for knex. There is need to upgrade bunch of webpack stuff to support es6 generated  knex, but I got it pretty much solved already during 0.16.0 release...

**Comment by fl0w** [comment]
Understood, again, was sort of hoping this was just a checklist miss.
I'll leave this open for others to see.

**Comment by elhigu** [comment]
>  I got it pretty much solved already during 0.16.0 release..

Tried out it yesterday briefly... looks like there are still some more problems to figure out.

**Comment by elhigu** [comment]
done 👍

**Comment by elhigu** [comment]
Thanks for notice! Probably parsing it has failed for some reason... will try to fix it. I think I need to setup some CI setup for docs building as well at some point...

**Comment by elhigu** [comment]
looks like its about rawgit shutting down... migrated to other similar service. Still there is js errors on docs page. I just add an issue about them (it might be that  "show full changelog" link doesn't work because of those errors)
