### ISSUE TITLE
Documentation for named foreign key constraint 

### ISSUE THREAD

**Issue by elhigu** [knex/documentation#21]
Was implemented in https://github.com/tgriesser/knex/pull/1726

**Comment by igor-savin-ht** [comment]
Implemented in #70

**Comment by elhigu** [comment]
Actually docs for .withKeyName() are still missing: https://github.com/tgriesser/knex/issues/2059

**Comment by igor-savin-ht** [comment]
@elhigu Np, I'll prepare the docs at some point next week, thanks for pointing out!
