### ISSUE TITLE
Typo in transactions block

### ISSUE THREAD

**Issue by colmer** [knex/documentation#228]
https://github.com/knex/documentation/blob/gh-pages/sections/transactions.js#L34
Need to delete this row

**Comment by kibertoad** [comment]
@colmer Need to double-check. The way I read it, there is a .then block attached to .transaction, and you want to move it to trx.insert block instead.

**Comment by colmer** [comment]
@kibertoad https://github.com/knex/documentation/blob/gh-pages/sections/transactions.js#L35 
close `knex.transaction(function(trx) {` and `.then` after it, not valid)

![Screenshot from 2019-08-09 12-23-03](https://user-images.githubusercontent.com/4122445/62765096-7f9c6380-baa0-11e9-8d75-461b1d48a9f3.png)

**Comment by colmer** [comment]
The same issue https://github.com/knex/documentation/blob/gh-pages/sections/transactions.js#L70

![Screenshot from 2019-08-09 12-31-45](https://user-images.githubusercontent.com/4122445/62765683-adce7300-baa1-11e9-879f-3dc0b6cab859.png)

Fix it too in request #229
