### ISSUE TITLE
How do you pronounce "knex"?

### ISSUE THREAD

**Issue by ricokahler** [knex/documentation#273]
A few co-workers and I were having a debate on how to say it so I thought I'd ask 😅

I was looking in the docs for how to pronounce it and no luck (sorry if I missed something!).

---

- It is like my favorite childhood toy "ken-nex"?
- Or is the k silent as in "nex"?
- Something else??

That's it. Thank you!

**Comment by elhigu** [comment]
https://github.com/knex/knex/issues/1879

**Comment by ricokahler** [comment]
@elhigu perfect. Are you accepting PRs to add this to the docs?

**Comment by elhigu** [comment]
Yep PR is welcome to clarify this.
