### ISSUE TITLE
There seems to be a problem with the official documents

### ISSUE THREAD

**Issue by lyd0** [knex/documentation#383]
https://knexjs.org/#Builder-distinct

![image](https://user-images.githubusercontent.com/29918052/150675018-9317993a-6528-4e79-8d94-8ee146ac83f8.png)

**Comment by OlivierCavadenti** [comment]
Fixed with https://github.com/knex/documentation/commit/3d403c6f9d562bc0f19933872c304cb37fc82cd3
Docs just needs to be published

**Comment by OlivierCavadenti** [comment]
fixed now
