### ISSUE TITLE
Incorrect docs for single `returning` value for Postgres

### ISSUE THREAD

**Issue by shellscape** [knex/documentation#389]
The documentation at https://knexjs.org/#Builder-returning contains the following:

```
// Returns [ { id: 1 } ]
knex('books')
  .returning('id')
  .insert({title: 'Slaughterhouse Five'})
Outputs:
insert into `books` (`title`) values ('Slaughterhouse Five')
```

While this may be true for other db platforms, it is not true for Postgres v12.7. Running an analog of that `insert` against our db, knex returns:

```
['46444ea2-71e6-4a6b-9cd4-a1e04161a970']
```

It's only when we specify `.returning(['id'])` in an array, that it returns the results as shown in the documentation.

This is a rather large error that could cause some significant grief for new adopters.

**Comment by kibertoad** [comment]
@shellscape Which knex version are you running? I think in 1.0.0+ it should be the way it is documented.

**Comment by shellscape** [comment]
I'm using v1.0.1

**Comment by kibertoad** [comment]
Interesting. That sounds like a bug, I will investigate.

**Comment by shellscape** [comment]
If that ends up as a bug, a fix to that will be a breaking change (just a heads up). We have quite a bit of code written around the different return types.

**Comment by kibertoad** [comment]
It was supposed to be a breaking change for 1.0.0, see https://github.com/knex/knex/blob/master/UPGRADING.md

**Comment by shellscape** [comment]
I just did a dive into our lockfile for the monorepo and it appears there's a condition that has one of our packages using v0.95.11. I think we can close this for now. I'll resolve this on my end and re-evaluate. Thanks for taking a look at this, apologies for any confusion. Happens from time to time in larger repos.

**Comment by kibertoad** [comment]
no worries! And I've just checked, we do have a test:
```
        it('should return the correct column when a single property is given to returning', () => {
          if (!isPostgreSQL(knex) && !isMssql(knex) && !isBetterSQLite3(knex)) {
            return;
          }

          return knex('accounts_foo')
            .insert({ balance_foo: 123 })
            .returning('balance_foo')
            .then((res) => {
              expect(res).to.eql([
                {
                  balance_foo: 123,
                },
              ]);
            });
        });
```

so pretty sure it should work as documented on PostgreSQL.

**Comment by npmDude** [comment]
This is also happening for MySQL. Can we reopen this issue or I need to open a new one?
