### ISSUE TITLE
Integrate Vitepress 

### ISSUE THREAD

**Issue by vencho-mdp** [knex/documentation#391]
Hi! A couple of weeks ago I told that I could migrate docs to Vuepress. Later on, I learnt that it'd be better to use vitepress for simplicity. Here is a really simple example of how it could be. Tell me what you think and the things we should change.

https://github.com/vencho-mdp/knex-docs-vitepress

Related to: #337

**Comment by stafyniaksacha** [comment]
Hey @vencho-mdp! I continued your work but on the main knex repos! https://github.com/knex/knex/pull/5121

What do you think?

**Comment by vencho-mdp** [comment]
It's great! Great Work!

**Comment by bobasch** [comment]
I guess this can be closed?
