### ISSUE TITLE
Documentation is misleading, wrong mentions to generic-pool 

### ISSUE THREAD

**Issue by danilohgds** [knex/documentation#65]
Can you guys please confirm what is the current lib being used for connection pooling?

In the documentation itself we have a statement saying pool2 is now being used:

> 
> Upgrading 0.11 -> 0.12
> generic-pool is swapped out for Pool2 for pooling management

While other pieces of the documentation mentions generic-pool... can you please address which technology is the one in place right now?

original issue :  https://github.com/tgriesser/knex/issues/2308#issuecomment-342137864

**Comment by elhigu** [comment]
According to changelog generic-pool has been used since 0.12.0.  For this whole `upgrading 0.11 -> 0.12` section should be deleted.

**Comment by wubzz** [comment]
`No occurrences of 'swapped out for Pool2' found` -- Looks like this might have been removed alongside 0.14 release?

Reopen if not!

**Comment by elhigu** [comment]
Yeah I removed that whole section when doing release, forgot to close this one 👍

**Comment by danilohgds** [comment]
Yeah, I checked the documentation and I no longer see any problems with pool2 being mentioned (Y)
